using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PRN232.LMS.API.Middleware;
using PRN232.LMS.Services.ResponseModels;
using PRN232.LMS.Repositories.Data;
using PRN232.LMS.Repositories.Implementations;
using PRN232.LMS.Repositories.Interfaces;
using PRN232.LMS.Services.Implementations;
using PRN232.LMS.Services.Interfaces;

var builder = WebApplication.CreateBuilder(args);

// ── Database ────────────────────────────────────────────────────────────────
builder.Services.AddDbContext<LmsDbContext>(options =>
    options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection")));

// ── Repository Layer ────────────────────────────────────────────────────────
builder.Services.AddScoped<ISemesterRepository, SemesterRepository>();
builder.Services.AddScoped<ICourseRepository, CourseRepository>();
builder.Services.AddScoped<ISubjectRepository, SubjectRepository>();
builder.Services.AddScoped<IStudentRepository, StudentRepository>();
builder.Services.AddScoped<IEnrollmentRepository, EnrollmentRepository>();

// ── Service Layer ───────────────────────────────────────────────────────────
builder.Services.AddScoped<ISemesterService, SemesterService>();
builder.Services.AddScoped<ICourseService, CourseService>();
builder.Services.AddScoped<ISubjectService, SubjectService>();
builder.Services.AddScoped<IStudentService, StudentService>();
builder.Services.AddScoped<IEnrollmentService, EnrollmentService>();

// ── API / Swagger ───────────────────────────────────────────────────────────
builder.Services.AddControllers()
    .AddJsonOptions(options =>
    {
        // Omit null properties (nested lists only filled on GetById; Errors null on success)
        options.JsonSerializerOptions.DefaultIgnoreCondition =
            System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull;
        // Safety net: ignore accidental EF navigation cycles
        options.JsonSerializerOptions.ReferenceHandler =
            System.Text.Json.Serialization.ReferenceHandler.IgnoreCycles;
    })
    .ConfigureApiBehaviorOptions(options =>
    {
        // Uniform 400 format for model validation failures (replaces ASP.NET default ProblemDetails)
        options.InvalidModelStateResponseFactory = context =>
        {
            var errors = context.ModelState.Values
                .SelectMany(v => v.Errors)
                .Select(e => e.ErrorMessage)
                .ToList();
            var response = ApiResponse<object>.Fail("Validation failed. Please check the submitted data.", errors);
            return new BadRequestObjectResult(response);
        };
    });
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new()
    {
        Title       = "PRN232 LMS API",
        Version     = "v1",
        Description = """
            ## Learning Management System REST API
            **PRN232 LAB 1** — 3-layer Architecture Demo

            ### Architecture
            - **API Layer** – Controllers (HTTP in/out only)
            - **Service Layer** – Business logic & mapping
            - **Repository Layer** – EF Core data access

            ### Response Format
            All endpoints return a consistent JSON envelope:
            ```json
            { "success": true, "message": "...", "data": {}, "errors": null }
            ```

            ### List Endpoints Support
            `?search=` `?sort=field,-field` `?page=1&size=10` `?fields=f1,f2` `?expand=relation`
            """,
        Contact = new()
        {
            Name  = "PRN232 Student",
            Email = "student@fpt.edu.vn"
        },
        License = new() { Name = "FPT University – Educational Use" }
    });

    // Load XML comments generated by <GenerateDocumentationFile>true</GenerateDocumentationFile>
    var xmlFile = $"{System.Reflection.Assembly.GetExecutingAssembly().GetName().Name}.xml";
    var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
    c.IncludeXmlComments(xmlPath, includeControllerXmlComments: true);

    // Group endpoints by tag (controller name) automatically
    c.TagActionsBy(api => new[] { api.GroupName ?? api.ActionDescriptor.RouteValues["controller"] });
    c.DocInclusionPredicate((_, _) => true);
});


// ── CORS (allow all for development) ────────────────────────────────────────
builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(policy =>
        policy.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod());
});

var app = builder.Build();

// ── Migrate & Seed on startup ────────────────────────────────────────────────
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<LmsDbContext>();
    await DbSeeder.SeedAsync(db);
}

// ── Middleware ───────────────────────────────────────────────────────────────
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(c =>
    {
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "PRN232 LMS API v1");
        c.RoutePrefix = string.Empty; // Swagger at root: https://localhost:{port}/
    });
}

// ── Global 500 handler (must be first middleware) ────────────────────────────
app.UseGlobalExceptionHandler();

app.UseCors();
app.UseHttpsRedirection();
app.UseAuthorization();
app.MapControllers();

app.Run();
